version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - gitlab:/var/opt/gitlab
      - gitlab:/var/log/gitlab
      - gitlab:/etc/gitlab
    networks:
      - gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password

        #  gitlab-runner:
        #    image: gitlab/gitlab-runner:alpine
        #    deploy:
        #      mode: replicated
        #      replicas: 4
        #    networks:
        #      - gitlab
        #

networks:
  gitlab:

volumes:
  gitlab:

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt
